# Generated by Django 4.1 on 2022-08-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Категория'),
        ),
    ]
